run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - errcheck
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  gofumpt:
    module-path: github.com/cdinu/myuplink-naive-client

issues:
  exclude-use-default: false
